test/events/eventbus.test.js, test/events/eventemitter.test.js, test/views/library-list/library-list.test.js, test/views/plugin-renderer/plugin-renderer.test.js
=> fix: add view tests

README.md
=> fix: update readme with shield badges

package-lock.json, src/components/header/header.js, src/components/sidenav/sidenav-item.js, src/utils/library.js, test/franklin-library.test.js, test/test-utils.js
=> fix: more coverage

package-lock.json, package.json, rollup.config.js, src/app.js, src/utils/library.js, src/views/library-list/library-list.js, test/franklin-library.test.js
=> fix: bugs, cleanup tests

index.html, src/app.js, src/components/header/header.js, src/components/sidenav/sidenav-item.js, src/events/events.js, src/plugins/blocks/blocks.js, src/utils/library.js, src/utils/plugin.js, src/views/library-list/library-list.js, src/views/plugin-renderer/plugin-renderer.js, test/plugins/block.test.js, test/utils/library.test.js, test/utils/plugin.test.js, test/views/library-list/library-list.test.js, test/views/plugin-renderer/plugin-renderer.test.js
=> fix: cleanup events and export events

README.md, index.html, rollup.config.js, src/app.js, src/models/app-model.js, src/plugins/blocks/blocks.css, src/plugins/blocks/blocks.js, src/utils/library.js, src/views/library-list/library-list.js, test/franklin-library.test.js, test/plugins/block.test.js, test/utils/library.test.js
=> fix: updates

README.md
=> fix: Readme updates

.github/workflows/semantic-release.yaml
=> fix: attempt to fix semantic release

.github/workflows/semantic-release.yaml
=> Semantic release

README.md, src/plugins/blocks/blocks.js, test/plugins/block.test.js
Changes:
Loads the blocks in parallel
Update README after some feedback
Handle block config with links that 404
=> fix: updates fixes

.github/workflows/release.yaml, src/models/app-model.js
=> fix: update host origin to hlx.live

README.md
Clarified some docs, added note about not working with auth'd sites.
=> chore: Docs update [skip ci]

README.md, src/components/block-list/block-list.js, src/components/block-renderer/block-renderer.js, src/components/header/header.js, src/plugins/blocks/blocks.js, src/utils/dom.js
Updates
1. Instead of removing the header/footer element, I'm hiding it instead. Removing was causing a lot errors in the console since `lib-franklin` assumes it exists in every page.
2. Added url params for the currently loaded plugin, the path to the block currently loaded and the index of the block. This will make way to fix Deeplinking in the future.
3. README update
=> Pre launch updates

.github/workflows/run-tests.yaml, src/components/block-list/block-list.js, test/components/block-renderer/block-renderer.test.js, test/components/block-renderer/fixures.js, test/franklin-library.test.js, test/plugins/block.test.js, web-test-runner.config.mjs
- Improve test coverage of blocks plugin
- Deploy codecov results on pushes to main
=> Test coverage

src/components/block-renderer/block-renderer.js
=> fix: include codeBasePath when loading

README.md, src/components/block-list/block-list.js, src/components/block-renderer/block-renderer.js, src/plugins/blocks/blocks.js, src/plugins/blocks/utils.js, test/components/block-list/block-list.test.js, test/components/block-renderer/block-renderer.test.js, test/fixtures/blocks.js, test/fixtures/libraries.js, test/fixtures/pages.js, test/fixtures/stubs/default-content.js, test/franklin-library.test.js, test/plugins/blocks/blocks.test.js
=> feat: autoblocks and default content support

src/components/block-list/block-list.js, src/components/header/header.js, src/plugins/blocks/blocks.js, test/fixtures/pages.js, test/franklin-library.test.js
=> feat: deep linking support

src/plugins/blocks/blocks.js, src/plugins/blocks/utils.js, test/plugins/blocks/blocks.test.js
=> fix: bad img url when copying default content + tests

src/views/plugin-renderer/plugin-renderer.js, test/views/plugin-renderer/plugin-renderer.test.js
=> fix: load plugin stylesheet before loading plugin js

src/components/block-renderer/block-renderer.js, test/plugins/blocks/blocks.test.js
=> fix: only change source tag urls when running in devMode

src/components/block-renderer/block-renderer.js, src/plugins/blocks/blocks.css, test/components/block-renderer/block-renderer.test.js
=> fix: add sidekick library class to body element

src/components/block-list/block-list.js, src/plugins/blocks/blocks.js, test/components/block-list/block-list.test.js, test/fixtures/blocks.js, test/fixtures/libraries.js, test/franklin-library.test.js
=> fix: store compound block flag in sectionMetadata instead of defaultMetadata

src/utils/dom.js, test/utils/dom.test.js
=> fix: don't try and parse descriptions in library metadata.. treat as HTML

src/plugins/blocks/utils.js, test/fixtures/stubs/cards.js, test/plugins/blocks/utils.test.js
=> fix: preserve data-align and data-valign when copying

README.md, src/plugins/blocks/blocks.js, test/plugins/blocks/blocks.test.js
=> #95: add support for custom viewport configurations

README.md
Recommend excluding example documents from index.
=> chore: recommend excluding from index
